- README.md
```kaggle datasets create``` does not have an ```-r``` flag, so it should be removed from the example
> Removing -r from datasets create example

- kaggle/api/kaggle_api_extended.py
Sometimes, sadly, we are asked to remove data files from past competitions.
> Warn when there is nothing to download

- .idea/vcs.xml
- setup.py
Currently, Installing this package has success, but kaggle command is failed by VersionConflict. (log below)
urllib3 1.23.0 has released in 2018-06-04.
But requests 2.18.4(latest) is limited urllib3's version to less than 1.23.0. ([source](https://github.com/requests/requests/blob/v2.18.4/setup.py#L47))
This limitation has already changed in requests. ([source]( https://github.com/requests/requests/commit/ac944b7439009ffbf7a10dfee35202f1ac090e76))
But this change have not released in pypi yet. 
For this reason, in this PR, I propose to limit urllib3's version as interim measures.
```
$ pip --no-cache-dir install kaggle
Collecting kaggle
Downloading https://files.pythonhosted.org/packages/46/79/3630c8a7c96c382a2c2e65445c1291ac12e36e868e5c390f348b1d4d6171/kaggle-1.3.9.1.tar.gz
Collecting …
```
> Limit urlib3's version to avoid requests 2.18.4's dependency

- README.md
- kaggle/api/kaggle_api_extended.py
This PR will make small changes to the Kaggle API to make it easier when 
working from an interactive session (or script in general).
- returning the meta_file from the function to create it
- ordering docs on creation in README so metadata is described first.
**dataset initialize**
Currently, when you create a metadata file, it doesn't return the path and the
user needs to set it manually, e.g.,:
```python
meta_file = '/tmp/datapackage.json'
client.dataset_initialize('/tmp')
```
Returning `meta_file` will allow for this:
```python
meta_file = client.dataset_initialize('/tmp')
```
**README ordering**
Going along with the above, the old order had the two creation commands come 
first, followed by the command to create the metadata. Since the creation
would warrant the metadata first (at …
> Minor tweaks for dataset creation 

- kaggle/api/kaggle_api_extended.py
This is another quick PR that will alert the user that the dataset creation takes time. We only print the message given that quiet is False.
Please feel free to critique the message itself, and if there are other spots in the API that need messages like this (I'd be happy to add, I haven't used the other endpoints so I don't know yet!)
> adding message to user that dataset creation takes time!

- README.md
- kaggle/api/kaggle_api_extended.py
- kaggle/tests/test_authenticate.py
This PR is mostly the same as #57, but just includes the changes to the authenticate function that (hopefully) will not be too complicated to discuss in a PR.  The design of the authenticate function is moduar so that the supporting functions can be used in different authentication flows, each of which is called from the primary authenticate:
```python
if os.path.exists(self.config):
config_data = self._authenticate_config(config_data)
config_data = self._authenticate_environment(config_data)
self._load_config(config_data)
```
The idea is that we should have a forward thinking mindset that other methods might be wanted, and it should be easy to add here.
I'm being very conservative because I spent a lot of time on the last PR, and most of the work now needs to be redone. This will part 1 …
> Obtain credentials from environment - attempt # 2

- README.md
The environment variables currently on the README for user and auth don't seem to work but these do. Maybe needs an update?
> Fix environment variables for Kaggle username and key

- kaggle/api/kaggle_api_extended.py
This is the first chunk of work (in a work in progress) to add docstrings to functions. I will likely need to go through this a few times, and it will take more than a day or two... will update and remove WIP when ready for review.
--------------------------------------------------------
I've finished the docstrings! I've made sure to do the following:
- spacing is consistent - I removed extra newlines
- when arguments are repeated for the "*_cli" functions, I reference the function being wrapped and only define the new arguments (to avoid definition twice and potential conflict).
- for one function (`initialize_kernel` metadata) there was an argument "kernel" that went in, but then wasn't used. I removed it, but if it was defined for a reason please let me know and I'll add it back!
- …
> Adding docstrings to functions

- README.md
In the following phrase there was no mention of the kernels API so I added it in myself.
The command line tool supports the following commands:
``` 
kaggle competitions {list,files,download,submit,submissions,leaderboard}
kaggle datasets {list, files, download, create, version, init}
kaggle kernels {list, init, push, pull, output, status}
kaggle config {view, set, unset}
```
> Add info about kernels API

- README.md
README.md - kaggle config said the default path is ~/.kaggle rather than current working directory.
> README.md - path default current working directory

- kaggle/api/kaggle_api_extended.py
If kaggle.json is not found and the credentials were also not set in the environment, raise an error showing the expected location of kaggle.json.
This solves the problem of exotic user folders. For example in my Python distribution the user folder is located inside of the distribution. I found that out by checking the value in `KaggleApi.config_dir`.
Before this PR, first the config file was read, followed by the environment. If there were credentials in the environment they would overwrite the ones from the config file. This behavior has been preserved, even though the environment is now read first. The config file is only checked if credentials were not found in the environment.
This is a small change, but I hope the more telling error message will help users quickly find the issue in …
> Show expected location when kaggle.json not found

- README.md
- kaggle/api/kaggle_api_extended.py
- kaggle/cli.py
This PR enables uploading non-flat datasets that include an arbitrary number of subfolders. Each subfolder is combined into a compressed or uncompressed archive and uploaded as a zip or tar file. The files are constructed in a way that leads to the same file hierarchy after the archives are automatically uncompressed by the backend and provided to Kernels (in `../input`).
> Support for uploading datasets with subfolders

- kaggle/api/kaggle_api_extended.py
> fix Python 2 error: 'file' object has no attribute 'readable' (issue #115)

- kaggle/api/kaggle_api_extended.py
Looked like most of the framework was there, I just added the configuration file parser changes to pick up the `ssl_ca_cert` from the `kaggle.json` file.
**Example Usage:**
```
{"username":"my_cool_username",
"key":"profile_api_key",
"ssl_ca_cert": "/Users/my_cool_username/evil_corp_ca_cert.pem",
"proxy": "http://proxy.evilcorp.com:80"}
```
This fixes #19
> Allow custom ca_cert files.

- kaggle/api/kaggle_api_extended.py
Parameter `quiet` has a default value of `True`, however the docstring mentions it to be `False`. This PR fixes the docstring accordingly.
> Align docstring with actual default value

- setup.py
Closes #147 
This increases urllib3 version restriction to `<1.25` as the one done by [requests](https://github.com/requests/requests/blob/v2.20.0/setup.py#L47).
> Increase urllib3 version restriction

- CHANGELOG.md
- KaggleSwagger.yaml
- kaggle/api/kaggle_api_extended.py
- kaggle/models/kaggle_models_extended.py
- kaggle/tests/test_authenticate.py
- setup.py
> Ability to add a model to a kernel

- setup.py
The official URLs will be added to the Project links section in the [pypi page](https://pypi.org/project/kaggle/).
> Add project links to the pypi page

- README.md
- integration_tests/test_models.py
- pyproject.toml
- tools/cicd/integration-tests.yaml
It uses the same setup as for kagglehub, and the same secrets.
Next: add a GCB trigger to run these tests on every PR
Obviously, the next big step is to test more surface of the CLI.
http://b/319074155
> Bootstrap integration tests

- pyproject.toml
- tools/GeneratePythonLibrary.sh
Issues:
- `hatch run install`: properly generate the CLI executable. http://b/333027353
- `hatch run compile` (`GeneratePythonLibrary.sh`) doesn't finish, and we're left with a mess of diffs.
Fix:
- I compared the script before and after move ([Webdiff](https://diff.googleplex.com/#key=8rusDEtbOkP2))
- Auditing all line diffs, one line caused the error pictured above. It seems `sed -i .bak` doesn't work for all versions of `sed`, and it was crashing the script, preventing the full compile flow from running.
- Some linux versions seem to require `sed -i.bak` (without the space). Removing the `.bak` functionality allowed the script to finish.
- FWIW I think it's fine to not create backups of the modified files, because we're version controlled anyways. 🤷 
Screen capture of the flow after …
> Fix GeneratePythonLibrary.sh script flow (`hatch run compile`)

- kaggle/api/kaggle_api_extended.py
- kaggle/test/test_authenticate.py
- src/kaggle/api/kaggle_api_extended.py
- src/kaggle/test/test_authenticate.py
When I was working on the last release I had got myself into a mixed-up state with too many unexpectedly-changed files. It was easiest to restore files rather than edit them and I lost the changes in this PR. These were from an external contributor in PR #540.
> Restore lost changes from #540

- .gitignore
- kaggle/api/kaggle_api_extended.py
- src/kaggle/api/kaggle_api_extended.py
Confirmed this fixes https://github.com/Kaggle/kaggle-api/issues/574 by building locally and successfully pushing a file that'd been edited in VSCode.
Note that it looks like there was a recent commit that didn't include the generation/auto-formatting that runs w/ `hatch run compile`, that seems to be responsible for the changes in .gitignore and the moving of `len` down a line--those changes appeared after running `hatch compile` even before I'd made any edits. If you'd prefer, I can drop those changes from this PR. Just let me know.
> Concatenate cells.source into a single string if it's a list

- src/KaggleSwagger.yaml
- src/kaggle/cli.py
Also, both the abbreviation or the full is accepted by the backend: https://github.com/Kaggle/kaggleazure/blob/aa12660a3bb6321ca2134110633571485ed049fc/Kaggle.Services.Models/Handlers/ModelApiService/V1/CreateModelInstanceHandler.cs#L118
Drive-by fix for the wiki URL.
> Add missing model licenses.

- kaggle/api/kaggle_api_extended.py
- src/kaggle/api/kaggle_api_extended.py
Some time in the last year the server stopped adding "Last-Modified" to some HTTP response headers. That broke the download file handler.
Fixes #622
> Allow last-modified to be absent from header

- kaggle/api/kaggle_api_extended.py
- src/kaggle/api/kaggle_api_extended.py
When I use the "kaggle kernel output" to download files, it always re-downloads files that already exist. Additionally, I found some issues in the kernels_output method.
1) When calling download_needed, the first parameter is url, but it expects a response object instead.
2) After fixing issue 1, the method does skip existing files. However, it’s still slow, and system monitoring tools show high network usage, indicating that the files are actually being downloaded again. The download_needed method only requires response.headers, but requests.get downloads the entire file by default. This can be fixed by setting the stream=True parameter to change the download behavior.
> [bugfix] download_needed param error in kernels_output

- kaggle/api/kaggle_api_extended.py
- kaggle/models/kaggle_models_extended.py
- kagglesdk/common/types/file_download.py
- kagglesdk/kaggle_client.py
- kagglesdk/kaggle_env.py
- kagglesdk/kaggle_http_client.py
- kagglesdk/kaggle_object.py
- pyproject.toml
- setup.py
- src/kaggle/api/kaggle_api_extended.py
- src/kaggle/models/kaggle_models_extended.py
- tests/unit_tests.py
The competitions portion of the API now uses `kagglesdk`.
The HTTP client has ben updated to use prod, if needed.
> Convert competitions to use kagglesdk

- pyproject.toml
- tools/GeneratePythonLibrary.sh
Switch to Google's open-source project formatting conventions, `yapf`, except preserve our 4-space indentation.
See #635 for results. If we need to change things even more, now is a good time for feedback.
> Use specific version of yapf to avoid format diffs

- kaggle/api/kaggle_api_extended.py
- kagglesdk/kaggle_http_client.py
- src/kaggle/api/kaggle_api_extended.py
- tests/unit_tests.py
Ignore `kaggle_http_client.py` because it is generated by `kapigen`.
I *did* reformat with yapf and still get format changes.
> Convert kaggle kernels API to use kagglesdk

- kagglesdk/test/test_client.py
Test initialization of KaggleEnv and KaggleClient, based on build_kaggle_client() in kaggle/api/kaggle_api_extended.py.
> Add simple unit test to kagglesdk.

- kaggle/models/dataset_new_request.py
- kaggle/models/dataset_new_version_request.py
- kaggle/models/dataset_update_settings_request.py
- kaggle/models/kernel_push_request.py
- kaggle/models/model_instance_new_version_request.py
- kaggle/models/model_instance_update_request.py
- kaggle/models/model_new_instance_request.py
- kaggle/models/model_new_request.py
- kaggle/models/model_update_request.py
- src/kaggle/models/dataset_new_request.py
- src/kaggle/models/dataset_new_version_request.py
- src/kaggle/models/dataset_update_settings_request.py
- src/kaggle/models/kernel_push_request.py
- src/kaggle/models/model_instance_new_version_request.py
- src/kaggle/models/model_instance_update_request.py
- src/kaggle/models/model_new_instance_request.py
- src/kaggle/models/model_new_request.py
- src/kaggle/models/model_update_request.py
These objects are used by `kaggle_api.py` but not the CLI. They will be removed in the GA release (unless we decide to continue supporting `kaggle_api.py`). I just copied them from an old version of the repo.
> Restore models used by kaggle_api.py

- kaggle/api/kaggle_api.py
- src/kaggle/api/kaggle_api.py
This file is used in a bit less than 4000 notebooks. I've tried to remap the functions to their CLI equivalents.
Some of the functions originally in this file separated file upload from some other function, like dataset creation. Since the CLI functions manage the upload, I did not implement those functions here, but left instructions on what to use instead. Not ideal, but we don't want the files getting uploaded twice.
This is completely untested, and I hope to fix that soon. The main items that need testing are those that write a metadata file, or have a large number of parameters.
> Add kaggle_api.py

- CHANGELOG.md
- kaggle/api/kaggle_api_extended.py
Fix escaped-quote issue in HTTP requests, and prepare for new beta release.
Note: I incremented the release number in a previous PR.
> Fix escaped-quote issue in HTTP requests

- .github/no-response.yaml
Copied from https://github.com/flutter/flutter-intellij/blob/master/.github/workflows/no-response.yaml, which I created a few years ago.
I added a new label `waiting for response`. Add that to an issue when asking for more info, and if there's no response in two weeks, it will be closed.
> Add a no response action to auto-close issues

- kagglesdk/kaggle_http_client.py
- src/kagglesdk/kaggle_http_client.py
Taken from the `requests` docs:
https://requests.readthedocs.io/en/latest/user/advanced/#prepared-requests
Fixes #727
> Merge envars before sending a request

- kaggle/api/kaggle_api_extended.py
- src/kaggle/api/kaggle_api_extended.py
These changes are entirely generated by `monkeytype`.
```bash
pip install monkeytype
cd tests
monkeytype run unit_tests.py
monkeytype apply kaggle.api.kaggle_api_extended
```
I first tried using `infer-types`. It didn't annotate parameters (but was easy to use). These annotations don't break anything, but I still want to generalize some types. I suspect `mypy` will complain, and I'll want to clean that up in a later PR.
For now, I'm keeping the database it built in case I want types on other files. The tests don't use `cli.py` (so `monkeytype` can't do anything for it) but I may just use the version of that produced by `infer-types`.
The `diff` used here doesn't show a diff, just delete all then add all. The changes are all just addition of type annotations to parameter plus return types.
> Add type annotations to main file

- kaggle/models/api_blob_type.py
- pyproject.toml
- tools/GeneratePythonLibrary.sh
- tools/releases/Dockerfile
Neither `yapf` or `autogen` is used any longer. Remove them, along with an unused file.
> Remove unused tools

- kaggle/api/kaggle_api_extended.py
- src/kaggle/api/kaggle_api_extended.py
- tests/unit_tests.py
- tools/GeneratePythonLibrary.sh
This adds `--failfast` to the test runner, which is usually what's needed (esp. if MT isn't running). But it could be problematic for some uses.
> Add test for dataset_delete() and make script more robust

- kagglesdk/kaggle_http_client.py
- kagglesdk/kernels/services/kernels_api_service.py
- kagglesdk/kernels/types/kernels_api_service.py
- kagglesdk/models/types/model_types.py
- src/kagglesdk/kaggle_http_client.py
- src/kagglesdk/kernels/services/kernels_api_service.py
- src/kagglesdk/kernels/types/kernels_api_service.py
- src/kagglesdk/models/types/model_types.py
@jplotts This has my latest with some of yours, too. No need to review, unless you want to.
The change to the http client is from Auto-Kaggle. I updated kapigen earlier, but not here.
And yes, some day (soonish) I need to start using the official `kagglesdk` repo. That's going to require more mucking about in the build and setup scripts, so I keep putting it off.
> Update kagglesdk with dataset_delete endpoint, etc

- kaggle/api/kaggle_api_extended.py
- kaggle/cli.py
- src/kaggle/api/kaggle_api_extended.py
- src/kaggle/cli.py
- tests/unit_tests.py
This was more involved than I expected. I noticed that `confirmation()` wasn't as informative as the generated code confirmation, but I thought a unified mechanism would be better. And it didn't make sense to `exit()` if the response was "no". If the confirmation had been done in the `_cli` then that would be OK, but it isn't. At least not today.
I haven't tested the `_cli` methods yet. I'm working on a PR (#766) to do so, but it needs to run against prod, so I need to deploy this first.
> Rename "yes" params and make confirmation consistent

- kaggle/cli.py
- src/kaggle/cli.py
Aliases were defined but not added to the allow-list. I shortened the names and added them.
Now you can just do:
`kaggle m i v files stevemessick/test-model/jax/main/1`
> Enable (and rename) synonyms i and v

- tools/GeneratePythonLibrary.sh
When run in `--watch` mode, `GeneratePythonLibrary.sh` tries to create the symlinks even though they exist already, which causes the script to fail. Therefore, only create symlinks if they don't exist already.
> Do not try to create the symlink if already exists in Generate script

- src/kaggle/__init__.py
- src/kaggle/api/kaggle_api_extended.py
- src/kaggle/cli.py
Since OAuth isn't enabled on the backend, we don't want to enable `kaggle auth login` by default for now but it is useful to have the functionality available for local testing and experimentation.
> Enable OAuth behind an environment variable

- src/kaggle/api/kaggle_api_extended.py
- src/kagglesdk/kaggle_http_client.py
Even if KAGGLE_API_TOKEN or legacy api key is set, we should not use it when `KaggleOAuth` to avoid confusion. It is possible user might be starting the OAuth flow to switch to another user so including existing tokens/keys can be very confusin and lead to errors.
> Do not use existing tokens/keys when executing an OAuth flow

- src/kagglesdk/kaggle_http_client.py
Turns out I introduced this bug in one of my earlier PRs when I removed `self._api_token` usage.
> Use self._api_token in kaggle_http_client to fix OAuth auth
