Kaggle/kaggle-api

README.md

removing `The biggest limitation at the moment is that kernels are not supported in any way at this point.  We do intend to implement support in the near future, though there's no ETA. `

Kernels ARE supported!

---

README.md

Creating a new dataset normally has two steps. At first, we should initiate a folder to be ready to upload files. It easily got confused for newbies.

Improve creating datasets document

---

README.md

update the readme with missing arguments in the updated version of  Kaggle - 1.5.1.1

Update Readme to 1.5.1.1

---

kaggle/api/kaggle_api_extended.py

Turn internet on by default

---

CHANGELOG.md
kaggle/api/kaggle_api_extended.py
setup.py

Release v1.5.9

---

CHANGELOG.md
kaggle/api/kaggle_api_extended.py
setup.py

updating changelog, api_extended and setup
https://buganizer.corp.google.com/issues/176834790

Update files for release of api version 1.5.11

---

kaggle/cli.py

This reverts commit 8c94809836ee9852947a862d46d0b5b5ba666115.

Revert accidental change

---

kaggle/api/kaggle_api_extended.py
kaggle/cli.py
kaggle/models/kaggle_models_extended.py
kaggle/test/test_authenticate.py
src/kaggle/api/kaggle_api_extended.py
src/kaggle/cli.py
src/kaggle/models/kaggle_models_extended.py
src/kaggle/test/test_authenticate.py

Some files were reformatted in my previous PR. After regenerating the files, the original formatting was restored. This PR simply reverts the format change.

Restore original formatting

---

docs/README.md

Use pip show command to view installed location of kaggle package

Update Readme - use pip show command

---

kaggle/api/kaggle_api_extended.py
src/kaggle/api/kaggle_api_extended.py

I asked for changes in #542 but did not get a reply. That change seemed like a good idea, so I'm making it here.

Re-do change in #542

---

kaggle/api/kaggle_api_extended.py

This PR improves the error handling for zip file operations in the code. Specifically, it addresses issues related to:
- `BadZipFile` errors, which occur when the downloaded file is corrupted or not a valid .zip file.
- `FileNotFoundError` for handling cases where the expected file is missing.
- `RuntimeError` for catching any unexpected errors during file operations.
Each exception now includes a message that directs users to report the issue at https://www.github.com/kaggle/kaggle-api.
This enhancement ensures better error reporting and guides users on how to proceed when encountering problems.
Linked Issue: #619

Improve Zip File Error Handling with Instructions

---

kaggle/api/kaggle_api_extended.py
kaggle/cli.py
kaggle/models/kaggle_models_extended.py
kaggle/test/test_authenticate.py
src/kaggle/api/kaggle_api_extended.py
src/kaggle/cli.py
src/kaggle/models/kaggle_models_extended.py
src/kaggle/test/test_authenticate.py
src/setup.py

Reformat everything

---

src/kaggle/api/kaggle_api_extended.py

I deleted some dead code, tested it, but forgot to copy into `src`.

Delete dead code

---

kaggle/api/kaggle_api_extended.py
kaggle/cli.py
kagglesdk/kaggle_object.py
src/kaggle/api/kaggle_api_extended.py
src/kaggle/cli.py
src/kagglesdk/kaggle_object.py
tests/unit_tests.py
tools/GeneratePythonLibrary.sh

This fixes a few problems found during the bug bash.
It also disables running the formatter.

Fix problems found during bug bash

---

kagglesdk/models/services/model_api_service.py
kagglesdk/models/types/model_api_service.py
kagglesdk/models/types/model_types.py
src/kagglesdk/admin/types/inbox_file_service.py
src/kagglesdk/blobs/types/blob_api_service.py
src/kagglesdk/common/types/file_download.py
src/kagglesdk/common/types/http_redirect.py
src/kagglesdk/competitions/services/competition_api_service.py
src/kagglesdk/competitions/types/competition_api_service.py
src/kagglesdk/datasets/types/dataset_api_service.py
src/kagglesdk/education/types/education_api_service.py
src/kagglesdk/kaggle_http_client.py
src/kagglesdk/kaggle_object.py
src/kagglesdk/kernels/types/kernels_api_service.py
src/kagglesdk/models/services/model_api_service.py
src/kagglesdk/models/types/model_api_service.py
src/kagglesdk/models/types/model_service.py
src/kagglesdk/models/types/model_types.py

This is the output from `kapigen` using the current proto files. All generated code.

Generate kagglesdk from latest protos

---

kagglesdk/kernels/types/kernels_api_service.py
kagglesdk/models/types/model_types.py

This is a bit early; if `max_session_execution_time` gets changed then I'll have to re-generate.
Reminder: generated code.

Update kagglesdk to latest protos

---

src/kagglesdk/kernels/types/kernels_api_service.py
src/kagglesdk/models/types/model_types.py

Update sdk in src

---

CHANGELOG.md
kaggle/api/kaggle_api_extended.py
kaggle/cli.py
kagglesdk/competitions/services/competition_api_service.py
kagglesdk/competitions/types/competition_api_service.py
src/kaggle/api/kaggle_api_extended.py
src/kaggle/cli.py
src/kagglesdk/competitions/services/competition_api_service.py
src/kagglesdk/competitions/types/competition_api_service.py

I *still* need to add a new test for the new API method.
Reminder: `kagglesdk` is generated.

Update new code to match new endpoint after its code review

---

docs/README.md

This will be in 1.7.4.1, which should go out today.

Add code comp submit example

---

CHANGELOG.md
kaggle/api/kaggle_api_extended.py
kaggle/cli.py
kagglesdk/kaggle_object.py
src/kaggle/api/kaggle_api_extended.py
src/kaggle/cli.py
src/kagglesdk/kaggle_object.py
tests/test_commands.sh

Also add help for the `--timeout` option.

Fix dataset download problem

---

kaggle/api/kaggle_api_extended.py

Misc clean-up. Remove unused imports, change a var name to avoid conflict with build-in name, improve some (not all) type hints, fix a bug.
Fixes #740

Improve some type hints and fix a bug

---

kaggle/api/kaggle_api_extended.py
src/kaggle/api/kaggle_api_extended.py

Fix calls to download_file()

---

pyproject.toml

This problem was first reported by @i-aki-y in #750.

Stop reformatting kagglesdk

---

docs/README.md
kaggle/api/kaggle_api_extended.py
kaggle/cli.py
kagglesdk/kaggle_http_client.py
src/kaggle/api/kaggle_api_extended.py
src/kaggle/cli.py
src/kaggle/configuration.py
tests/unit_tests.py

The change to `src/kaggle/configuration.py` should have been in a previous PR. The change to `kagglesdk` has been made in `kapigen` already.

Add kaggle delete dataset

---

kaggle/api/kaggle_api_extended.py
src/kaggle/api/kaggle_api_extended.py

Check dataset status before uploading

---

kaggle/api/kaggle_api_extended.py
src/kaggle/api/kaggle_api_extended.py

Fix bug that caused double serialization

---

tests/test_commands.sh

This is still not perfect but will do for now.

Add tests for delete and de-flake

---

kaggle/api/kaggle_api_extended.py
src/kaggle/api/kaggle_api_extended.py

https://screenshot.googleplex.com/78ZNQrwapBv5S3b
http://b/416341332

Allow user to specify docker_image during kernel push

---

kaggle/api/kaggle_api_extended.py
src/kaggle/api/kaggle_api_extended.py

https://screenshot.googleplex.com/8GwAdfVrSwADp5W
http://b/417413172

Output docker_image as part of the pull metadata

---

kagglesdk/kaggle_env.py
kagglesdk/kaggle_http_client.py
src/kagglesdk/kaggle_env.py
src/kagglesdk/kaggle_http_client.py

This doesn't include changes for Quick Versions, although kapigen did generate it. I didn't want to include it if it wasn't ready.
http://b/379083750

Update kagglesdk to use short-term auth tokens on KKB

---

docs/README.md
kaggle/api/kaggle_api_extended.py
kagglesdk/datasets/types/dataset_api_service.py
kagglesdk/datasets/types/dataset_enums.py
src/kaggle/api/kaggle_api_extended.py
src/kagglesdk/datasets/types/dataset_api_service.py
src/kagglesdk/datasets/types/dataset_enums.py

Update `kagglesdk` and add 'parquet' to dataset filter options.

Add parquet as a filter option

---

src/kagglesdk/competitions/types/competition_api_service.py
src/kagglesdk/kaggle_http_client.py
src/kagglesdk/models/types/model_api_service.py

@pnorgaard You'll need this once the back-end updates have been applied.

Get latest from kapigen

---

src/kagglesdk/kaggle_object.py

Backend already supports `camelCase`, `PascalCase`, `snake_case` and `UPPER_SNAKE_CASE` when deserializing enum values so this change should be safe.
Duration isn't used in any existing method so it is also a safe change. Backend expects the proto-json standard where duration is serialized as "<seconds>.<nanos>s".

Use proto-json format when serializing enums and durations
